[package]
name = "saltator"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "saltator"
path = "src/main.rs"

[dependencies]
saltator-cluster.workspace = true
saltator-core.workspace = true
saltator-cs-api.workspace = true
saltator-federation.workspace = true
saltator-media.workspace = true
saltator-roomserver.workspace = true
saltator-shard.workspace = true
saltator-store.workspace = true
saltator-userserver.workspace = true
saltator-fedout.workspace = true

ruma.workspace = true

anyhow.workspace = true
axum.workspace = true
axum-server.workspace = true
chacha20poly1305 = { workspace = true }
clap.workspace = true
rand.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true
reqwest.workspace = true
