[package]
name = "saltator-federation"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
saltator-core.workspace = true
saltator-roomserver.workspace = true
saltator-userserver.workspace = true
saltator-media.workspace = true

axum.workspace = true
ruma.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
thiserror.workspace = true
tokio.workspace = true
reqwest.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
saltator-shard.workspace = true
saltator-store.workspace = true
serde_json.workspace = true
tempfile.workspace = true
axum-server.workspace = true
rcgen.workspace = true
rustls.workspace = true
