[package]
name = "saltator-roomserver"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
saltator-core.workspace = true
blake3.workspace = true
saltator-shard.workspace = true
saltator-store.workspace = true

ruma.workspace = true
serde.workspace = true
serde_json.workspace = true
postcard.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
openraft.workspace = true

[dev-dependencies]
tempfile.workspace = true
anyhow.workspace = true
